apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: webapp
spec:
  nodeSelector:
    app: hostapp
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: web-content
      mountPath: /usr/share/nginx/html
  volumes:
  - name: web-content
    configMap:
      name: web-config